FROM docker.elastic.co/logstash/logstash:7.16.1

LABEL maintainer="Ilija Vukotic <ivukotic@cern.ch>"

USER root
RUN yum install -y nmap

# USER logstash

RUN mkdir /usr/share/logstash/configs

COPY logstash.yml /usr/share/logstash/config/logstash.yml
COPY configs/StashCP.conf /usr/share/logstash/configs/StashCP.conf
COPY pipelines/stashcp.yml /usr/share/logstash/config/pipelines.yml