FROM docker.elastic.co/logstash/logstash:8.3.1

LABEL maintainer="Ilija Vukotic <ivukotic@cern.ch>"

USER root
# RUN yum install -y nmap

# USER logstash

RUN mkdir /usr/share/logstash/configs

COPY logstash.yml /usr/share/logstash/config/logstash.yml
COPY configs/varnish.conf /usr/share/logstash/configs/varnish.conf
COPY pipelines/varnish.yml /usr/share/logstash/config/pipelines.yml
COPY filters/* /usr/share/logstash/filters/