FROM docker.elastic.co/logstash/logstash:9.2.2

LABEL maintainer="Ilija Vukotic <ivukotic@cern.ch>"

USER root

RUN mkdir /usr/share/logstash/configs
RUN mkdir /usr/share/logstash/filters
RUN mkdir /var/log/logstash && chown -R logstash /var/log/logstash

COPY logstash.yml /usr/share/logstash/config/logstash.yml
COPY configs/event-loop.conf /usr/share/logstash/configs/event-loop.conf
COPY pipelines/event-loop.yml /usr/share/logstash/config/pipelines.yml
COPY filters/* /usr/share/logstash/filters/

USER logstash
