FROM docker.elastic.co/logstash/logstash:8.4.0

LABEL maintainer="Ilija Vukotic <ivukotic@cern.ch>"

USER root
RUN apt-get update && apt-get install -y nmap

# USER logstash

RUN mkdir /usr/share/logstash/configs

COPY logstash.yml /usr/share/logstash/config/logstash.yml
COPY configs/AF.conf /usr/share/logstash/configs/AF.conf
COPY pipelines/af.yml /usr/share/logstash/config/pipelines.yml