FROM docker.elastic.co/logstash/logstash:7.16.1

LABEL maintainer="Ilija Vukotic <ivukotic@cern.ch>"

USER root
RUN yum install -y nmap

# add postgresql driver
RUN mkdir -p /usr/share/logstash/java/
RUN curl https://jdbc.postgresql.org/download/postgresql-42.3.1.jar -o /usr/share/logstash/java/postgresql-42.3.1.jar
# USER logstash

RUN mkdir /usr/share/logstash/configs

COPY logstash.yml /usr/share/logstash/config/logstash.yml
COPY configs/rucio-x1t.conf /usr/share/logstash/configs/rucio-x1t.conf
COPY pipelines/rucio-x1t.yml /usr/share/logstash/config/pipelines.yml