
FROM docker.elastic.co/logstash/logstash:9.5.3

LABEL maintainer="Ilija Vukotic <ivukotic@cern.ch>"

USER root

RUN mkdir /usr/share/logstash/configs
RUN mkdir /var/log/logstash && chown -R logstash /var/log/logstash

COPY logstash.yml /usr/share/logstash/config/logstash.yml

COPY configs/netstat.conf /usr/share/logstash/configs/netstat.conf

COPY pipelines/netstat.yml /usr/share/logstash/config/pipelines.yml

# COPY filters/* /usr/share/logstash/filters/

USER logstash
