FROM docker.elastic.co/logstash/logstash:8.4.0

LABEL maintainer="Ilija Vukotic <ivukotic@cern.ch>"

USER root

RUN apt-get update && apt-get install -y nmap


# RUN bin/logstash-plugin install logstash-input-stomp

RUN mkdir /usr/share/logstash/configs

COPY logstash.yml /usr/share/logstash/config/
COPY configs/xcache_gstream.conf /usr/share/logstash/configs/
COPY pipelines/xcache_gstream.yml /usr/share/logstash/config/pipelines.yml
