FROM docker.elastic.co/logstash/logstash:9.1.3

LABEL maintainer="Ilija Vukotic <ivukotic@cern.ch>"

USER root
RUN apt-get update && apt-get install -y nmap

# add postgresql driver
RUN mkdir -p /usr/share/logstash/java/

RUN mkdir /usr/share/logstash/configs
RUN mkdir /var/log/logstash && chown -R logstash /var/log/logstash

COPY logstash.yml /usr/share/logstash/config/logstash.yml

COPY configs/ai_logger.conf /usr/share/logstash/configs/ai_logger.conf

COPY pipelines/ai_logger.yml /usr/share/logstash/config/pipelines.yml

# COPY filters/* /usr/share/logstash/filters/

USER logstash