FROM docker.elastic.co/logstash/logstash:9.1.3

LABEL maintainer="Ilija Vukotic <ivukotic@cern.ch>"

USER root

RUN mkdir /usr/share/logstash/configs
RUN mkdir /var/log/logstash && chown -R logstash /var/log/logstash

COPY logstash.yml /usr/share/logstash/config/logstash.yml

COPY configs/servicey.conf /usr/share/logstash/configs/servicey.conf

COPY pipelines/servicey.yml /usr/share/logstash/config/pipelines.yml

USER logstash