FROM docker.elastic.co/logstash/logstash:7.12.0

LABEL maintainer="Ilija Vukotic <ivukotic@cern.ch>"

USER root
RUN yum install -y nmap

# USER logstash

RUN mkdir /usr/share/logstash/configs

COPY logstash.yml /usr/share/logstash/config/logstash.yml
COPY configs/MemoryMonitor.conf /usr/share/logstash/configs/MemoryMonitor.conf
COPY pipelines/memory-monitor.yml /usr/share/logstash/config/pipelines.yml