FROM docker.elastic.co/logstash/logstash:8.18.2

LABEL maintainer="Ilija Vukotic <ivukotic@cern.ch>"

USER root

RUN apt-get update && apt-get install -y nmap && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*


# add postgresql driver
RUN mkdir -p /usr/share/logstash/java/

RUN mkdir /usr/share/logstash/configs
RUN mkdir /var/log/logstash && chown -R logstash /var/log/logstash

COPY logstash.yml /usr/share/logstash/config/logstash.yml

COPY configs/frontier.conf /usr/share/logstash/configs/frontier.conf

COPY pipelines/frontier.yml /usr/share/logstash/config/pipelines.yml

# COPY filters/* /usr/share/logstash/filters/

USER logstash