FROM docker.elastic.co/logstash/logstash:9.1.3

LABEL maintainer="Ilija Vukotic <ivukotic@cern.ch>"

RUN mkdir /usr/share/logstash/configs
RUN mkdir /var/log/logstash && chown -R logstash /var/log/logstash

COPY logstash.yml /usr/share/logstash/config/logstash.yml
COPY configs/AF.conf /usr/share/logstash/configs/AF.conf
COPY pipelines/af.yml /usr/share/logstash/config/pipelines.yml

USER logstash
