# only collectors.yaml should be recreated.
# If services are recreated, collector.atlas-ml.org should be updated to point to them.

kind: Service
apiVersion: v1
metadata:
  name: uc-ls-xcache-gstream
  namespace: aaas
  annotations:
    metallb.universe.tf/allow-shared-ip: "uc-logstash"
  labels:
    k8s-app: uc-ls-xcache-gstream
spec:
  type: LoadBalancer
  loadBalancerIP: 192.170.227.237
  ports:
    - name: http-for-gstream
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    k8s-app: uc-ls-xcache-gstream
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uc-ls-xcache-gstream
  namespace: aaas
  labels:
    k8s-app: uc-ls-xcache-gstream
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: uc-ls-xcache-gstream
  template:
    metadata:
      labels:
        k8s-app: uc-ls-xcache-gstream
    spec:
      containers:
        - name: uc-ls-xcache-gstream
          image: atlasanalyticsservice/uc_ls_xcache_gstream:latest
          # command: ["sleep"]
          # args: ["infinity"]
          env:
            - name: LOGSTASH_PWD
              valueFrom:
                secretKeyRef:
                  name: logstash-pwd
                  key: password
