input {
  http {
    port => 8080
    response_code => 200
    codec => json
    max_content_length => 104857600
  }
}

filter {
  if [headers][http_user_agent] != "xAODRootAccess" {
    drop {}
  }
  mutate {
    add_field => { "from" => "%{[headers][from]}" }
    remove_field => ["headers", "host"]
  }

  json {
    source => "message"
    remove_field => [ "message" ]
    tag_on_failure => ["_jsonparsefailure"]
  }
  
  ruby {
    code => '
      containers = event.get("accessedContainers")
      if containers.is_a?(Array)
        event.set("accessedContainers", containers.map { |obj|
          { "name" => obj.keys.first, "count" => obj.values.first }
        })
      end
      branches = event.get("accessedBranches")
      if branches.is_a?(Array)
        event.set("accessedBranches", branches.map { |obj|
          { "name" => obj.keys.first, "count" => obj.values.first }
        })
      end
    '
  }

  mutate {
    # remove_field => [ "counters" ]
    remove_field => [ "version" ]
    remove_field => [ "@version" ]
  }

}

output {

  #  stdout {
  #    codec => rubydebug
  #  }

    if "_jsonparsefailure" in [tags] {
      file {
        path => "/var/log/logstash/jsonparsefailure.txt"
      }
    } else {
      elasticsearch {
        hosts => "atlas-kibana.mwt2.org"
        ssl_enabled => true
        index => 'event-loop'
        user => "uc_logstash_indexer"
        password => "${LOGSTASH_PWD}"
      }

#        file {
#            path => "/var/log/logstash/correct.txt"
#        }

    }
    
    # file {
    #   path => "/var/log/logstash/all.txt"
    # }

}