input {
  tcp {
    # host => "0.0.0.0"
    port => "8080"
    codec => json
    ssl_client_authentication => none
    dns_reverse_lookup_enabled => false
    tcp_keep_alive => true
  }
}

filter {
  if ![requestURI] {
    drop {}
  }
  if [frontier-id] =~ /^[0-9]+_[0-9]+$/ {
    ruby {
      code => '
        fid = event.get("frontier-id")
        if fid
          parts = fid.split("_", 2)
          if parts.length == 2
            event.set("task_id", parts[0].to_i)
            event.set("job_id", parts[1].to_i)
            event.remove("frontier-id")
          end
        end
      '
    }
  }
  mutate {
    remove_field => [ "mdc", "logger", "host", "message", "msg", "logger_name", "port", "type", "token" ]
  }
}

output {

  #  stdout {
  #    codec => rubydebug
  #  }
  
  if "_jsonparsefailure" in [tags] {
    file {
      path => "/var/log/logstash/json_parse_failure.txt"
    }
  }
  
  elasticsearch {
    hosts => "atlas-kibana.mwt2.org"
    ssl_enabled => true
    index => 'neo_frontier_write'
    user => "uc_logstash_indexer"
    password => "${LOGSTASH_PWD}"
  }

}
