input {
  tcp {
    # host => "0.0.0.0"
    port => "8080"
    codec => json
    ssl_client_authentication => none
    dns_reverse_lookup_enabled => false
    tcp_keep_alive => true
  }
}

filter {
  if ![requestURI] {
    drop {}
  }
  mutate {
    remove_field => [ "mdc", "logger", "host", "message", "msg", "logger_name", "port", "type", "token" ]
  }
}

output {

  #  stdout {
  #    codec => rubydebug
  #  }
  
  if "_jsonparsefailure" in [tags] {
    file {
      path => "/var/log/logstash/json_parse_failure.txt"
    }
  }
  
  elasticsearch {
    hosts => "atlas-kibana.mwt2.org"
    ssl_enabled => true
    index => 'neo_frontier_write'
    user => "uc_logstash_indexer"
    password => "${LOGSTASH_PWD}"
  }

}
