input {
  http {
    port => "8081"
  }
}

filter {
  
  mutate {
    remove_field => [ "headers", "type", "program", "host" ]
  }

    
  mutate {
    rename => {"message" => "input_message"}
  }
  grok {
        patterns_dir => "/usr/share/logstash/patterns/"
        match => { "input_message" => "{%{GREEDYDATA:message_kv}, 'message': %{GREEDYDATA:message}}" }
  }

  kv {
    source => "message_kv"
    trim_key => "'"
    trim_value => "',"
    value_split => ":"
  }
  mutate {
    convert => {"PilotTimeStamp" => "string"}
  }
  ruby {
    code => "
        timestamp_source = (event.get('[PilotTimeStamp]')).split(/\s|\./)
        event.set('[@timestamp_nanoseconds]', ((Time.at(timestamp_source[0].to_i).getutc).strftime('%Y-%m-%dT%H:%M:%S.') +  timestamp_source[1] + 'Z') )
        event.set('[@timestamp]', LogStash::Timestamp.new(event.get('[@timestamp_nanoseconds]')) )
      "
  }
  
  mutate {
    remove_field => [ "message_kv", "input_message", "version", "@version" ]
    remove_field => [ "PilotTimeStamp", "@timestamp_nanoseconds" ]
    remove_field => [ "[extra][func_name]", "[extra][logger_name]", "[extra][line]", "[extra][path]", "[extra][logstash_async_version]", "[extra][process_name]", "[extra][thread_name]" ]
    convert => { "RequestID" => "integer" }
    convert => { "PandaJobID" => "integer" }
    convert => { "TaskID" => "integer" }
    convert => { "Harvester_WorkerID" => "integer" }
  }
}

output {

  #  stdout {
  #    codec => rubydebug
  #  }
  
  # file {
  #   path => "/var/log/logstash/all.txt"
  # }


  elasticsearch {
    hosts => "atlas-kibana.mwt2.org"
    ssl => true
    action => "create"
    index => 'pilot_log'
    user => "uc_logstash_indexer"
    password => "${LOGSTASH_PWD}"
  }
  
  
}