input {
  http {
    port => "8081"
  }
}

filter {
  
  mutate {
    remove_field => [ "headers", "type" ]
    gsub => ["message", "'", '"']
  }

  json {
    source => "message"
    remove_field => [ "message" ]
    remove_field => [ "port" ]
    tag_on_failure => ["_jsonparsefailure"]
  }
  
  # ruby { path => "/usr/share/logstash/filters/reformat.rb" }
  
  mutate {
    remove_field => [ "version" ]
    remove_field => [ "@version" ]
    # remove_field => [ "host" ]
  }

}

[2024-10-04T17:59:31,409][WARN ][logstash.filters.json    ][pilot_log]
[9fc6fe456ad9f7522f2fb0236af35eb23e44fbbb9e13207e7d0707303e3ded3a] 
Error parsing json {:source=>"message", 
:raw=>"{
'TaskID': '41547794', 
'PandaJobID': '6356703513', 
'Harvester_WorkerID': '628885473', 
'Harvester_ID': 'CERN_central_A', 
'RequestID': 245061, 
'PilotTimeStamp': 1728064763.2951524, 
'message': 'AnalysisBase_VHbb::exe... INFO    Event number = 78400'
}", :exception=>
#<LogStash::Json::ParserError: Unexpected character (''' (code 39)): was expecting double-quote to start field name

output {

  #  stdout {
  #    codec => rubydebug
  #  }
  
  file {
    path => "/var/log/logstash/all.txt"
  }

  if "_jsonparsefailure" in [tags] {
    file {
      path => "/var/log/logstash/jsonparsefailure.txt"
    }
  } else {
    elasticsearch {
      hosts => "atlas-kibana.mwt2.org"
      ssl => true
      index => 'pilot_log'
      user => "uc_logstash_indexer"
      password => "${LOGSTASH_PWD}"
    }
  }
  
}