input {
  http {
    # host => "0.0.0.0"
    port => "80"
  }
}

filter {
  
  mutate {
    remove_field => [ "headers" ]
  }

  json {
    source => "message"
    remove_field => [ "headers" ]
    remove_field => [ "message" ]
    remove_field => [ "port" ]
    tag_on_failure => ["_jsonparsefailure"]
    target => "sites"
  }
  
  mutate {
    remove_field => [ "counters" ]
    remove_field => [ "version" ]
    remove_field => [ "@version" ]
    remove_field => [ "host" ]
  }

  ruby {
    code => '
      sites = event.get("sites")
      return unless sites.is_a?(Hash)

      sites.each do |url, status|
        new_event = event.clone

        new_event.set("url",            url)
        new_event.set("return_status",  status)

        new_event.remove("sites")
        new_event.remove("message")

        yield new_event          # push the child event downstream
      end

      event.cancel               # drop the original container event
    '
  }

  
}

output {

  #  stdout {
  #    codec => rubydebug
  #  }

    if "_jsonparsefailure" in [tags] {
      file {
        path => "/var/log/logstash/varnish_jsonparsefailure.txt"
      }
    } else {
      elasticsearch {
        hosts => "atlas-kibana.mwt2.org"
        ssl => true
        index => 'varnish_status'
        user => "uc_logstash_indexer"
        password => "${LOGSTASH_PWD}"
      }

#        file {
#            path => "/var/log/logstash/correct.txt"
#        }

    }
  

}