name: Build frontier Logstash dockerhub image

on:
  push:
    branches:
      - "frontier"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.frontier
          push: true
          tags: |
            atlasanalyticsservice/uc_ls_frontier:latest
            atlasanalyticsservice/uc_ls_frontier:${{ github.sha }}

      - name: Repository Dispatch
        env:
          GH_TOKEN: ${{ secrets.AAAS_GITOPS_DEPLOY_TRIGGER }}
        run: |
          gh api repos/maniaclab/flux_apps/dispatches \
            -f event_type=gitops-uc-ls-frontier-app-trigger \
            -F "client_payload[ref]=${{ github.ref }}" \
            -F "client_payload[sha]=${{ github.sha }}"
