name: Build Xenon1T rucio Logstash dockerhub image

on:
  push:
    branches:
      - "rucio-x1t"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: atlasanalyticsservice/uc_ls_rucio_x1t
          dockerfile: Dockerfile_rucio_x1t
          tags: latest, ${{ github.sha }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.AAAS_GITOPS_DEPLOY_TRIGGER }}
          repository: maniaclab/river_apps
          event-type: gitops-uc-ls-x1t-rucio-app-trigger
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
